# Importing Library

In [6]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Loading data

In [7]:
PCOS_inf = pd.read_csv("PCOS_infertility.csv")
PCOS_woinf = pd.read_csv("PCOS_W_infertility.csv")

In [8]:
PCOS_inf.info()
# Col: AMH(ng/mL) cotains numerical values as strings

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sl. No                  541 non-null    int64
 1   Patient File No.        541 non-null    int64
 2   PCOS (Y/N)              541 non-null    int64
 3     I   beta-HCG(mIU/mL)  541 non-null    float64
 4   II    beta-HCG(mIU/mL)  541 non-null    float64
 5   AMH(ng/mL)              541 non-null    object
dtypes: float64(2), int64(3), object(1)
memory usage: 25.5+ KB

In [9]:
PCOS_woinf.info()
# Null values:
# N460(mrriage status)
# AH158(FastFood)
# col: AMH(ng/mL) cotains numerical values as strings

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Sl. No                 541 non-null    int64
 1   Patient File No.       541 non-null    int64
 2   PCOS (Y/N)             541 non-null    int64
 3    Age (yrs)             541 non-null    int64
 4   Weight (Kg)            541 non-null    float64
 5   Height(Cm)             541 non-null    float64
 6   BMI                    541 non-null    float64
 7   Blood Group            541 non-null    int64
 8   Pulse rate(bpm)        541 non-null    int64
 9   RR (breaths/min)       541 non-null    int64
 10  Hb(g/dl)               541 non-null    float64
 11  Cycle(R/I)             541 non-null    int64
 12  Cycle length(days)     541 non-null    int64
 13  Marraige Status (Yrs)  540 non-null    float64
 14  Pregnant(Y/N)          541 non-null    int64
 15  No. of aborptions      541 non-null    int64
 16  FSH(mIU/mL)            541 non-null    float64
 17  LH(mIU/mL)             541 non-null    float64
 18  FSH/LH                 541 non-null    float64
 19  Hip(inch)              541 non-null    int64
 20  Waist(inch)            541 non-null    int64
 21  Waist:Hip Ratio        541 non-null    float64
 22  TSH (mIU/L)            541 non-null    float64
 23  AMH(ng/mL)             541 non-null    object
 24  PRL(ng/mL)             541 non-null    float64
 25  Vit D3 (ng/mL)         541 non-null    float64
 26  PRG(ng/mL)             541 non-null    float64
 27  RBS(mg/dl)             541 non-null    float64
 28  Weight gain(Y/N)       541 non-null    int64
 29  hair growth(Y/N)       541 non-null    int64
 30  Skin darkening (Y/N)   541 non-null    int64
 31  Hair loss(Y/N)         541 non-null    int64
 32  Pimples(Y/N)           541 non-null    int64
 33  Fast food (Y/N)        540 non-null    float64
 34  Reg.Exercise(Y/N)      541 non-null    int64
 35  BP _Systolic (mmHg)    541 non-null    int64
 36  BP _Diastolic (mmHg)   541 non-null    int64
 37  Follicle No. (L)       541 non-null    int64
 38  Follicle No. (R)       541 non-null    int64
 39  Avg. F size (L) (mm)   541 non-null    float64
 40  Avg. F size (R) (mm)   541 non-null    float64
 41  Endometrium (mm)       541 non-null    float64
 42  Unnamed: 42            2 non-null      object
dtypes: float64(18), int64(23), object(2)
memory usage: 181.9+ KB

# Preprocessing

In [10]:
# Merging two dataset
data = pd.merge(PCOS_woinf,PCOS_inf, on='Patient File No.', suffixes=('','_y'),how='left')

# Eliminating repeated column after merging
data =data.drop(['Unnamed: 42', 'Sl. No_y', 'PCOS (Y/N)_y', 'AMH(ng/mL)_y'], axis=1)

data.head()

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm),I beta-HCG(mIU/mL),II beta-HCG(mIU/mL)
0,1,10001,0,28,44.6,152.0,19.300000,15,78,22,...,0,110,80,3,3,18.0,18.0,8.5,1.99,1.99
1,2,10002,0,36,65.0,161.5,24.921163,15,74,20,...,0,120,70,3,5,15.0,14.0,3.7,60.80,1.99
2,3,10003,1,33,68.8,165.0,25.270891,11,72,18,...,0,120,80,13,15,18.0,20.0,10.0,494.08,494.08
3,4,10004,0,37,65.0,148.0,29.674945,13,72,20,...,0,120,70,2,2,15.0,14.0,7.5,1.99,1.99
4,5,10005,0,25,52.0,161.0,20.060954,11,72,18,...,0,120,80,3,4,16.0,14.0,7.0,801.45,801.45

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 541 entries, 0 to 540
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sl. No                  541 non-null    int64
 1   Patient File No.        541 non-null    int64
 2   PCOS (Y/N)              541 non-null    int64
 3    Age (yrs)              541 non-null    int64
 4   Weight (Kg)             541 non-null    float64
 5   Height(Cm)              541 non-null    float64
 6   BMI                     541 non-null    float64
 7   Blood Group             541 non-null    int64
 8   Pulse rate(bpm)         541 non-null    int64
 9   RR (breaths/min)        541 non-null    int64
 10  Hb(g/dl)                541 non-null    float64
 11  Cycle(R/I)              541 non-null    int64
 12  Cycle length(days)      541 non-null    int64
 13  Marraige Status (Yrs)   540 non-null    float64
 14  Pregnant(Y/N)           541 non-null    int64
 15  No. of aborptions       541 non-null    int64
 16  FSH(mIU/mL)             541 non-null    float64
 17  LH(mIU/mL)              541 non-null    float64
 18  FSH/LH                  541 non-null    float64
 19  Hip(inch)               541 non-null    int64
 20  Waist(inch)             541 non-null    int64
 21  Waist:Hip Ratio         541 non-null    float64
 22  TSH (mIU/L)             541 non-null    float64
 23  AMH(ng/mL)              541 non-null    object
 24  PRL(ng/mL)              541 non-null    float64
 25  Vit D3 (ng/mL)          541 non-null    float64
 26  PRG(ng/mL)              541 non-null    float64
 27  RBS(mg/dl)              541 non-null    float64
 28  Weight gain(Y/N)        541 non-null    int64
 29  hair growth(Y/N)        541 non-null    int64
 30  Skin darkening (Y/N)    541 non-null    int64
 31  Hair loss(Y/N)          541 non-null    int64
 32  Pimples(Y/N)            541 non-null    int64
 33  Fast food (Y/N)         540 non-null    float64
 34  Reg.Exercise(Y/N)       541 non-null    int64
 35  BP _Systolic (mmHg)     541 non-null    int64
 36  BP _Diastolic (mmHg)    541 non-null    int64
 37  Follicle No. (L)        541 non-null    int64
 38  Follicle No. (R)        541 non-null    int64
 39  Avg. F size (L) (mm)    541 non-null    float64
 40  Avg. F size (R) (mm)    541 non-null    float64
 41  Endometrium (mm)        541 non-null    float64
 42    I   beta-HCG(mIU/mL)  541 non-null    float64
 43  II    beta-HCG(mIU/mL)  541 non-null    float64
dtypes: float64(20), int64(23), object(1)
memory usage: 190.2+ KB

In [12]:
# Numerical data with dtype objective
data["AMH(ng/mL)"].head()

0    2.07
1    1.53
2    6.63
3    1.22
4    2.26
Name: AMH(ng/mL), dtype: object

Here in the data set, one column has numerical values in string format 
and Two column has null values: Marraige Status (Yrs), Fast food (Y/N)

In [13]:
# Converting string to numerical format
data["AMH(ng/mL)"] = pd.to_numeric(data["AMH(ng/mL)"], errors='coerce')

#Filling the null values
data['Marraige Status (Yrs)'].fillna(data['Marraige Status (Yrs)'].median(),inplace=True)
data['Fast food (Y/N)'].fillna(data['Fast food (Y/N)'].median(),inplace=True)
data['AMH(ng/mL)'].fillna(data['AMH(ng/mL)'].median(),inplace=True)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 541 entries, 0 to 540
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sl. No                  541 non-null    int64
 1   Patient File No.        541 non-null    int64
 2   PCOS (Y/N)              541 non-null    int64
 3    Age (yrs)              541 non-null    int64
 4   Weight (Kg)             541 non-null    float64
 5   Height(Cm)              541 non-null    float64
 6   BMI                     541 non-null    float64
 7   Blood Group             541 non-null    int64
 8   Pulse rate(bpm)         541 non-null    int64
 9   RR (breaths/min)        541 non-null    int64
 10  Hb(g/dl)                541 non-null    float64
 11  Cycle(R/I)              541 non-null    int64
 12  Cycle length(days)      541 non-null    int64
 13  Marraige Status (Yrs)   541 non-null    float64
 14  Pregnant(Y/N)           541 non-null    int64
 15  No. of aborptions       541 non-null    int64
 16  FSH(mIU/mL)             541 non-null    float64
 17  LH(mIU/mL)              541 non-null    float64
 18  FSH/LH                  541 non-null    float64
 19  Hip(inch)               541 non-null    int64
 20  Waist(inch)             541 non-null    int64
 21  Waist:Hip Ratio         541 non-null    float64
 22  TSH (mIU/L)             541 non-null    float64
 23  AMH(ng/mL)              541 non-null    float64
 24  PRL(ng/mL)              541 non-null    float64
 25  Vit D3 (ng/mL)          541 non-null    float64
 26  PRG(ng/mL)              541 non-null    float64
 27  RBS(mg/dl)              541 non-null    float64
 28  Weight gain(Y/N)        541 non-null    int64
 29  hair growth(Y/N)        541 non-null    int64
 30  Skin darkening (Y/N)    541 non-null    int64
 31  Hair loss(Y/N)          541 non-null    int64
 32  Pimples(Y/N)            541 non-null    int64
 33  Fast food (Y/N)         541 non-null    float64
 34  Reg.Exercise(Y/N)       541 non-null    int64
 35  BP _Systolic (mmHg)     541 non-null    int64
 36  BP _Diastolic (mmHg)    541 non-null    int64
 37  Follicle No. (L)        541 non-null    int64
 38  Follicle No. (R)        541 non-null    int64
 39  Avg. F size (L) (mm)    541 non-null    float64
 40  Avg. F size (R) (mm)    541 non-null    float64
 41  Endometrium (mm)        541 non-null    float64
 42    I   beta-HCG(mIU/mL)  541 non-null    float64
 43  II    beta-HCG(mIU/mL)  541 non-null    float64
dtypes: float64(21), int64(23)
memory usage: 190.2 KB

In [15]:
# data.to_csv('PCOS_Final_Data.csv')